apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
    name: istio-system-access
    namespace: istio-system
rules:
- apiGroups: ['', 'extensions', 'apps']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
    name: istio-system-access
    namespace: istio-system
subjects:
- kind: ServiceAccount
  name: istio-user
  namespace: istio-tutorial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-system-access
  