apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
    name: istio-access
rules:
- apiGroups: ['', 'extensions', 'apps', 'networking.k8s.io', 'networking.istio.io', 'authentication.istio.io', 'rbac.istio.io', 'config.istio.io']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
    name: istio-access
subjects:
- kind: ServiceAccount
  name: istio-user
  namespace: istio-tutorial
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: istio-access